Iter23
gam6itko/go-musthave-metrics pull request #24
Opened 2024-05-11 18:59 UTC by gam6itko

2024-05-13 19:23 UTC, tmvrus requested changes
<img width="620" alt="image" src="https://github.com/gam6itko/go-musthave-metrics/assets/554425/fb010391-8a8f-40d3-baa7-696e4fa1fd19">

как в агенте реализовано это требование?

2024-05-13 19:23 UTC, tmvrus commented on cmd/agent/main.go
> +				if err2 != nil {
err2 это прям чудо креатива

2024-05-13 19:23 UTC, tmvrus commented on cmd/server/middleware.go
> +		}
тут ошибка

2024-05-13 19:23 UTC, tmvrus commented on internal/server/controller/metrics.go
> +		log.Fatal(err2)
фыв

2024-05-13 19:23 UTC, tmvrus commented on cmd/agent/main.go
> +					break infLoop
а зачем так если можно просто return?

2024-05-15 11:18 UTC, gam6itko commented on cmd/agent/main.go
> +				if err2 != nil {
Линтеры ругаются если затеняешь переменную err, так что иногда я использую err2. Но это не тот случай. Поправил.

2024-05-15 11:46 UTC, gam6itko commented on internal/server/controller/metrics.go
> +		log.Fatal(err2)
Если я правильно понял, то вам не нравится креативное название "err2"? Тут поправил на у `err`

2024-05-15 11:49 UTC, gam6itko commented on cmd/agent/main.go
> +					break infLoop
Мне казалось, что выйти из цикла более правильнее, ведь после него может быть еще какой-нибудь код (что-то сделать напоследок).

2024-05-15 11:52 UTC, gam6itko commented on cmd/agent/main.go
> +					break infLoop
Поменял на return.

2024-05-15 16:07 UTC, gam6itko commented
@tmvrus В агенте реализовано так:

- Запущены 3 горутины (2 собирают метрики, одна отправляет). 

- Перед запуском кадой горутины запускаем wg.Add(1)`.

https://github.com/gam6itko/go-musthave-metrics/blob/791a0eee4e99c83f119f0507e84d93753a03a2f1/cmd/agent/main.go#L95

- Передаём каждой горутине контекст, который отменяется по сигналу ОС.

https://github.com/gam6itko/go-musthave-metrics/blob/791a0eee4e99c83f119f0507e84d93753a03a2f1/cmd/agent/main.go#L88

- Каждая горутина запускает бесконечный цикл. 

- В начале каждой итерации цикла проверяется не завершился ли контекст. 

https://github.com/gam6itko/go-musthave-metrics/blob/791a0eee4e99c83f119f0507e84d93753a03a2f1/cmd/agent/main.go#L101

- Если контекст завершился, то выходим из бесконечного цикла и делаем `wg.Done`.

https://github.com/gam6itko/go-musthave-metrics/blob/791a0eee4e99c83f119f0507e84d93753a03a2f1/cmd/agent/main.go#L97

- После запуска горутин запускаем http-сервер для профайлинга.

- После запуска http-сервера ждём завершения горутин 

https://github.com/gam6itko/go-musthave-metrics/blob/791a0eee4e99c83f119f0507e84d93753a03a2f1/cmd/agent/main.go#L151

2024-05-16 11:49 UTC, tmvrus approved these changes

2024-05-16 14:24 UTC, merged