Iter25
gam6itko/go-musthave-metrics pull request #26
Opened 2024-05-24 19:22 UTC by gam6itko

# gRPC

Для gRPC не реализовано:
- подпись (заголовок HashSHA256)
- шифрование
- проверка X-Real-IP на сервере.

т.к. в уроке этого не было, а я пока что не имею понятия как это делать.

## agent

- Добавил опцию UseGRPC (USE_GRPC, -use-grpc). Если она установлена, то вместо отправки метрик по HTTP используется gRPC. Опция ADDRESS будет подставлена в адрес gRPC-сервера.
- Провёл рефакторинг. Шифрование, подпись, и добавление X-Real-IP теперь в декораторах.
- Изменил отправку метрик на сервер. Одна горутина формирует слайс метрик и отправляет его в канал, который слушает горутина2 и отправляет на сервер.

## server
- Добавлена настройка GRPC_ADDRESS, если она установлена, то будет запущен и gRPC сервер тоже.
- Имеется логирование входящих запросов.

2024-05-27 15:41 UTC, tmvrus requested changes

2024-05-27 15:41 UTC, tmvrus commented on cmd/agent/main.go
>  	sync2 "github.com/gam6itko/go-musthave-metrics/internal/sync"
какой креативный нейминг

2024-05-27 15:41 UTC, tmvrus commented on cmd/server/grpc.go
> +	listen, err := net.Listen("tcp", ":3200")
<img width="731" alt="image" src="https://github.com/gam6itko/go-musthave-metrics/assets/554425/b1ceb8ba-9a82-478d-9188-6a778e617551">
каким образом порт конфигурится для http?

2024-05-27 15:41 UTC, tmvrus commented on internal/agent/http/client.go
> +	req.Header.Set("X-Real-IP", ths.ip.String())
<img width="715" alt="image" src="https://github.com/gam6itko/go-musthave-metrics/assets/554425/b07b7c3b-5dcb-4e8a-9ecd-4df72e936cbd">

а где гарантия что это значение имеет хоть какое то отношение к реальному адресу агента?

2024-05-27 18:02 UTC, gam6itko commented on internal/agent/http/client.go
> +	req.Header.Set("X-Real-IP", ths.ip.String())
Никакой гарантии нет. Это значение вообще берётся из конфига. Это имитация reverse-proxy. Тем самым мы можем проверить работу настройки server trustet_subnet.

2024-05-27 18:06 UTC, gam6itko commented on cmd/agent/main.go
>  	sync2 "github.com/gam6itko/go-musthave-metrics/internal/sync"
Полагаю, что вы про http2. Это GoLand так придумал, авторство его.
Я переименовал в `agent_http`

2024-05-27 18:07 UTC, gam6itko commented on cmd/server/grpc.go
> +	listen, err := net.Listen("tcp", ":3200")
Тут мой косяк. Поправил.

2024-05-28 19:41 UTC, tmvrus approved these changes

2024-05-28 23:23 UTC, merged