Iter5
gam6itko/go-musthave-metrics pull request #5
Opened 2023-12-08 08:29 UTC by gam6itko

2023-12-11 09:08 UTC, tmvrus requested changes
автотесты содержат ошибки
```
=== NAME  TestIteration4
    iteration4_test.go:154: Процесс завершился с не нулевым статусом 2
    iteration4_test.go:166: Получен STDOUT лог процесса:
        
        sending metrics: 5
        client: errors making http request: Post "http://localhost:33669/update/gauge/Alloc/103336": EOF
        client: errors making http request: Post "http://localhost:33669/update/counter/PollCount/5": dial tcp 127.0.0.1:33669: connect: connection refused
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6228cd]
        
        goroutine 7 [running]:
        main.startReporting.func1.1(0x704260?, {0xc000128000, 0x1c, 0x14?}, 0xc00003efa8?)
        	/__w/go-musthave-metrics/go-musthave-metrics/cmd/agent/main.go:[19](https://github.com/gam6itko/go-musthave-metrics/actions/runs/7139100337/job/19441820728#step:12:20)1 +0x8ad
        main.startReporting.func1()
        	/__w/go-musthave-metrics/go-musthave-metrics/cmd/agent/main.go:192 +0x133
        created by main.startReporting in goroutine 1
        	/__w/go-musthave-metrics/go-musthave-metrics/cmd/agent/main.go:1[24](https://github.com/gam6itko/go-musthave-metrics/actions/runs/7139100337/job/19441820728#step:12:25) +0xd8
        	```
https://github.com/gam6itko/go-musthave-metrics/actions/runs/7139100337/job/19441820728

2023-12-11 09:39 UTC, gam6itko commented
@tmvrus Добрый день. Я не совсем понял какие автотесты содержат ошибка? Ваши или мои. 
Я вижу что все последнии github-actions в каждом MR завершены успешно. Только что я проверил на своём компьютере мои автотесты, они тоже завершились успехом.

Их лога который вы предоставили сложно понять о чём идеёт речь. Я вижу что там написано `TestIteration4` но MR iter4 у меня прошёл все проверки.

2023-12-11 09:53 UTC, gam6itko commented
@tmvrus Я прошерстил логи actions и понял о чём вы. Починил.

2023-12-12 13:45 UTC, tmvrus approved these changes

2023-12-12 13:45 UTC, tmvrus commented on cmd/server/main.go
> +	}
ListenAndServe всегда возвращает ошибку, иногда эта ошибка значит что "все прошло хорошо", но условие err != nil все равно будет выполнятся, следовательно, код всегда будет паниковать. Это не всегда нужно.

2023-12-12 13:45 UTC, tmvrus commented on internal/common/flags/net_address.go
> +}
ценность этого кода весьма сомнительна, с таким же успехом можно передавать параметр конфигурации в http.ListenAndServe и все эти проверки будут выполнены точно так же, какой смысл сначала парсить строки на хост и порт, чтобы затем снова собирать вместе - неясно.

2023-12-12 13:45 UTC, tmvrus commented on internal/server/storage/memory/main.go
> +	return 0, false
можно было обойтись без if
val, exist := storage.gauge[name]
return val, exists

`zero value` для float64 это и будет 0

2023-12-12 13:45 UTC, tmvrus commented on internal/server/storage/memory/main.go
> +	storage.counter[name] += val
можно сразу прибавлять, без проверки 
https://play.golang.com/p/qwNdClAdSnH

2023-12-12 13:45 UTC, tmvrus commented on cmd/agent/main.go
> +					resp, err := httpClient.Do(req)
если случится ошибка при создании http-запроса, то клиент все равно его выполнит, что вряд ли приведет к чему-то хорошему

2023-12-12 13:45 UTC, tmvrus commented on cmd/agent/main.go
> +				resp, err := httpClient.Do(req)
тут тоже самое

2023-12-12 13:45 UTC, tmvrus commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(reportInterval) * time.Second)
`time.Duration(reportInterval) * time.Second` можно вычислить один раз перед входом в цикл, в текущей реализации вычисление происходит на каждой итерации

2023-12-12 15:40 UTC, gam6itko commented on cmd/server/main.go
> +	}
поправил

2023-12-12 15:55 UTC, gam6itko commented on internal/common/flags/net_address.go
> +}
@tmvrus  Идея была в том, что пользователь может передать в аргументах хост без порта. Я думал назначить порт по-умолчанию. Я убрал использование этого кода на серверной части.

По вашему использование этого кода на агенте тоже излишне?

2023-12-12 16:03 UTC, gam6itko commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(reportInterval) * time.Second)
поправил

2023-12-12 17:20 UTC, gam6itko commented on cmd/agent/main.go
> +					resp, err := httpClient.Do(req)
поправил

2023-12-12 17:23 UTC, gam6itko commented on internal/server/storage/memory/main.go
> +	return 0, false
поправил

2023-12-12 19:20 UTC, merged

2023-12-13 10:18 UTC, tmvrus commented on internal/common/flags/net_address.go
> +}
Любой написанный код нужно сопровождать, тратить на него какие-то ресурсы. По это причине лучше не писать код который от нас не требуется, в контексте задачи не подразумевалось что пользователь может передать хост без порта или порт без хоста.